question_data = [
	{"type": "boolean", "difficulty": "easy", "category": "Science &amp; Nature",
	 "question": "Celiac Disease is a disease that effects the heart, causing those effected to be unable to eat meat.",
	 "correct_answer": "False", "incorrect_answers": ["True"]},
	{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
	 "question": "The game &quot;Battlefield 1&quot; takes place during World War I.",
	 "correct_answer": "True", "incorrect_answers": ["False"]},
	{"type": "boolean", "difficulty": "easy", "category": "Celebrities",
	 "question": "Tupac Shakur died due to complications from being stabbed in 1996.",
	 "correct_answer": "False", "incorrect_answers": ["True"]},
	{"type": "boolean", "difficulty": "easy",
	 "category": "Entertainment: Japanese Anime &amp; Manga",
	 "question": "Studio Ghibli is a Japanese animation studio responsible for the films &quot;Wolf Children&quot; and &quot;The Boy and the Beast&quot;.",
	 "correct_answer": "False", "incorrect_answers": ["True"]},
	{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
	 "question": "The Konami Code is known as Up, Up, Down, Down, Left, Right, Right, Left, B, A, Start.",
	 "correct_answer": "False", "incorrect_answers": ["True"]},
	{"type": "boolean", "difficulty": "easy", "category": "Animals",
	 "question": "The Axolotl is an amphibian that can spend its whole life in a larval state.",
	 "correct_answer": "True", "incorrect_answers": ["False"]},
	{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Board Games",
	 "question": "There is a Donald Trump Board Game, which was made in 1989.",
	 "correct_answer": "True", "incorrect_answers": ["False"]},
	{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
	 "question": "In Kingdom Hearts the Paopu fruit is said to intertwine the destinies for two people forever.",
	 "correct_answer": "True", "incorrect_answers": ["False"]},
	{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
	 "question": "Minecraft can be played with a virtual reality headset.",
	 "correct_answer": "True", "incorrect_answers": ["False"]},
	{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
	 "question": "In RuneScape, one must complete the &quot;Dragon Slayer&quot; quest before equipping Rune Platelegs.",
	 "correct_answer": "False", "incorrect_answers": ["True"]}
]
